### PR TITLE
Cleaning up apt packages.

### PR DESCRIPTION
**Pull request by sudermanjr**
According to https://github.com/sipcapture/homer/wiki/Example:-GeoIP the commented out section is unnecessary in Debian.

I added a the geo-ip extras module which gives you the GeoIPCity.dat which is already referenced in the kamailio.cfg.

### CODE REVIEW

**Comment by sudermanjr** [comment]
Not sure why this build is failing.  I looked and it appears to have nothing to do with these changes

```
The command "docker exec -it mysql mysql -u root -p'secret' -s -e "SELECT * FROM homer_data.sip_capture_call_$(date '+%Y%m%d')\G" | grep -i "proxy auth"" exited with 1.
0.02s$ curl -s -o /dev/null -w "%{http_code}" localhost | grep -iP "^200$"
200```

**Comment by sudermanjr** [comment]
Any chance of getting this merged?

**Comment by dougbtv** [comment]
Thanks for circling back @sudermanjr -- looks like the failing tests are actually unrelated. Let's merge it in, looks like a net benefit. Thanks for the submission, too!

**Comment by sudermanjr** [comment]
Thanks!

**Pull request merged**
