### PR TITLE
Startup fix: rotation.ini and run.sh

### PR DESCRIPTION
**Pull request by davidcsi**
- Fixed rotation.ini to add "usesocket" and set "host" properly to "mysql"
- Fixed cron/run.sh to set the paths to rotation.ini and homer_rotate
properly.
Docker now starts properly.

### CODE REVIEW

**Comment by adubovikov** [comment]
Hi, I am not sure about host, why did you set "mysql" ?

**Comment by davidcsi** [comment]
Hello,

It's the container alias for mysql. If i don't set that, homer_rotate fails.

David

**Review by dougbtv — APPROVED** [review]
+1 this LGTM. I'm actually kinda surprised that it worked at all in the past with `host=localhost` somehow? That fix makes sense to me. 

Additionally, thinking that the difference for `/opt/new/*` to `/opt/*` paths reflects more recent changes in Homer, and this is GoodWork™ so thanks for catching that (since there's no nightly builds).

Additionally, unsure why the PR on github doesn't show this, but, it also passes -- build here: https://travis-ci.org/sipcapture/homer-docker/builds/208357666

So, LGTM! Thanks!!

**Comment by adubovikov** [comment]
@dougbtv please do merge :-)
@davidcsi  thank you!

**Comment by davidcsi** [comment]
Thanks guys!

**Pull request merged**
